const String KProudectColletion = "Products";
const String KProudectName = "ProductName";
const String KProudectDescription = "ProductDescription";
const String KProudectCatogery = "ProductCatogery";
const String KProudectLoction = "ProductLoction";
const String KProudectPrice = "ProductPrice";
const String KProudectPrand = "ProductPrand";
const String KProudectCondation = "ProductCondation";
const String Kcover = "Cover";
const String KcoverPhoto = "CoverPhoto";
const String KorederDetiles = "OrdarDetils";
const kTotallPrice = 'TotallPrice';
const String Koreder = "Ordar";
const String KQantan = "Ordar";
String LName, add, city, gov, pN;
String FName = "[]";
List<String> addres;
String tast;
const kAddress = 'Address';
